version: '3'

services:
  postgresdb:
    image: postgresdb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Test_1234
    volumes:
    - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: